config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  post 'top/login'
  root 'top#main'
  get 'top/logout'
  resources :top
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid]
      render 'main'
    else
      render 'login'
    end
  end
  def new
    @user = User.new
  end
  def create
    uid = params[:user][:uid]
    pass = BCrypt::Password.create(params[:user][:pass])
    @user = User.new(uid: uid, pass: pass)
    @user.save
    redirect_to '/'
  end
  def login
    if User.find_by(uid: params[:uid])
      user_code = User.find_by(uid: params[:uid])
      login_pass = user_code.pass
      if BCrypt::Password.new(login_pass) == params[:pass]
        session[:login_uid] = params[:uid]
        redirect_to root_path
      else
        render 'login_failed'
      end
    else
      render 'login_failed'
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
  <%= label_tag :uid, 'ユーザID' %>
  <%= text_field_tag :uid %>
  <%= label_tag :pass, 'パスワード' %>
  <%= text_field_tag :pass %>
  <%= submit_tag 'ログイン' %>
<% end %>
<br>
<p><%= link_to '新規登録', 'top/new' %></p>

app/views/top/login_failed.html.erb
ログイン失敗！
<%= link_to '戻る', :back %>

app/views/top/main.html.erb
ログイン中です！
<%= link_to 'ログアウト', top_logout_path %>

app/views/top/new.html.erb
<%= form_for @user , url: {action: :create} do |f| %>
  <%= f.label :uid, 'ID' %>
  <%= f.text_field :uid %>
　<%= f.label :pass, 'パスワード' %>
  <%= f.text_field :pass %>
  <%= f.submit '登録' %>
<% end %>